from abc import ABC, abstractmethod

class BaseLLMClient(ABC):
    """
    Abstract base class for all LLM clients.

    Defines the interface that all LLM client implementations
    must follow to generate text based on prompts.
    """

    @abstractmethod
    def generate(self, prompt: str, **kwargs) -> str:
        """
        Generate text using the LLM client.

        Args:
            prompt (str): Input prompt to send to the LLM.
            **kwargs: Additional keyword arguments specific to the LLM implementation.

        Returns:
            str: Text generated by the LLM.
        """
        pass
