import sys
import os
from pathlib import Path
import re
import json
import logging
from dotenv import load_dotenv
from src.prompt_engineering.templates import load_prompt_template
from src.handlers.error_handler import handle_errors, MeetingMindError
from src.llm.deepseek_client import DeepSeekV3Client
from langchain_core.prompts import PromptTemplate
from langchain.output_parsers import PydanticOutputParser
from pydantic import BaseModel, Field 
from typing import Optional, List

# Load environment variables from .env
load_dotenv()

# Ensure project root is available for imports
PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))


TASKS_DIR = PROJECT_ROOT / "data" / "analysis_outputs" / "tasks"
TASKS_DIR.mkdir(parents=True, exist_ok=True)

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")


class Task(BaseModel):
    """Represents a single actionable task extracted from a meeting."""
    task: str
    person: Optional[str]
    deadline: Optional[str]
    
class TaskList(BaseModel):
    """Container for a list of extracted tasks."""
    tasks: List[Task]

class TaskExtractor:
    """
    TaskExtractor identifies and extracts actionable tasks from unstructured
    meeting transcripts using the DeepSeek-V3 model via OpenRouter API.
    
    It converts raw meeting discussion into structured task metadata, including:
    - task descriptions
    - responsible persons (if mentioned)
    - deadlines or due dates (if mentioned)

    Responsibilities:
    - Load and format prompt templates for task extraction.
    - Communicate with the LLM to parse and interpret meeting text.
    - Produce structured JSON-like task data validated through Pydantic.
    - Save results to disk for downstream project management workflows.
    """
    def __init__(self, client = None):
        """
        Initialize TaskExtractor.

        Args:
            client (optional): Custom LLM client instance (e.g., DeepSeekV3Client). 
                If None, initializes DeepSeekV3Client with API key from environment (OPENROUTER_API_KEY).
        """
        self.parser = PydanticOutputParser(pydantic_object=TaskList)
        self.prompt_template = load_prompt_template("task_extraction")
        self.client = client or DeepSeekV3Client(api_key=os.getenv("OPENROUTER_API_KEY"))


    @handle_errors("Failed to extract tasks")
    def extract_tasks(self, transcript: str) -> list[dict]:
        """
        Extract actionable tasks from a transcript.

        Args:
            transcript (str):
                Raw meeting transcript text.

        Returns:
            list[dict]:
                A list of structured task dictionaries. Example:
                [
                    {
                        "task": "Prepare Q4 financial report",
                        "person": "Alice",
                        "deadline": "2025-01-15"
                    }
                ]

        Raises:
            MeetingMindError:
                If task extraction fails unexpectedly.
        """

        prompt = PromptTemplate(
            template=self.prompt_template,
            input_variables=["transcript"],
            partial_variables={"format_instructions" : self.parser.get_format_instructions()}
        )
    
        prompt = prompt.format(transcript=transcript)

        tasks = self.client.generate(prompt=prompt, output_parser=self.parser)

        logging.info(f"Extracted {len(tasks.tasks)} tasks")
        return [task.dict() for task in tasks.tasks]
    
    def save_tasks(self, tasks: list[dict], output_file: str = None) -> str:
        """
        Save extracted tasks to a JSON file.

        Args:
            tasks (list[dict]):
                List of task dictionaries generated by extract_tasks().
            output_file (str, optional):
                Custom path for saving the output file.
                Defaults to: data/analysis_outputs/tasks/tasks.json

        Returns:
            str: Absolute file path to the saved JSON task file.
        """
        if output_file is None:
            output_file = TASKS_DIR / "tasks.json"
        else:
            output_file = Path(output_file)
        with open(output_file, "w", encoding="utf-8") as f:
            json.dump(tasks, f, ensure_ascii=False, indent=2)
        logging.info(f"Tasks saved to {output_file}")
        return str(output_file)

